export const SAMPLE_DOCS = [
  {
    id: "isg",
    name: "İSG Kanunu",
    file: "isg-kanunu.pdf",
    desc: "6331 Sayılı İş Sağlığı ve Güvenliği",
    pages: 28,
    tone: "full",
  },
  {
    id: "kvkk",
    name: "KVKK",
    file: "kkvk.pdf",
    desc: "6698 Sayılı Kişisel Verilerin Korunması",
    pages: 21,
    tone: "full",
  },
  {
    id: "sgk",
    name: "SGK / GSS Kanunu",
    file: "sgk-gss-kanunu.pdf",
    desc: "5510 Sayılı Sosyal Sigortalar",
    pages: 242,
    tone: "full",
  },
  {
    id: "sendikalar",
    name: "Sendikalar Kanunu",
    file: "sendikalar-toplu-is-sozlesmesi-kanunu.pdf",
    desc: "6356 Sayılı Sendikalar ve Toplu İş",
    pages: 39,
    tone: "full",
  },
  {
    id: "borclar",
    name: "Borçlar Kanunu",
    file: "turk-borclar-kanunu.pdf",
    desc: "6098 Sayılı Türk Borçlar Kanunu",
    pages: 134,
    tone: "full",
  },
  {
    id: "tuketici",
    name: "Tüketici Koruma",
    file: "tuketici-koruma-kanunu.pdf",
    desc: "6502 Sayılı Tüketici Hakları",
    pages: 53,
    tone: "full",
  },
  {
    id: "sermaye",
    name: "Sermaye Piyasası",
    file: "semaye-piyasasi-kanunu.pdf",
    desc: "6362 Sayılı Sermaye Piyasası",
    pages: 113,
    tone: "full",
  },
  {
    id: "ticaret",
    name: "Ticaret Kanunu",
    file: "turk-ticaret-kanunu.pdf",
    desc: "6102 Sayılı Türk Ticaret Kanunu",
    pages: 409,
    tone: "full",
  },
  {
    id: "is_kanunu",
    name: "İş Kanunu Özeti",
    file: "is_kanunu_ozet.pdf",
    desc: "4857 Sayılı İş Kanunu",
    pages: 1,
    tone: "summary",
  },
  {
    id: "bankacilik",
    name: "Bankacılık Mevzuat Özeti",
    file: "bankacilik_mevzuat.pdf",
    desc: "BDDK Düzenlemeleri",
    pages: 1,
    tone: "summary",
  },
] as const;

export const SAMPLE_DOC_FILENAMES = new Set<string>(
  SAMPLE_DOCS.map((sample) => sample.file),
);
